apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: ns-quota
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: 
      limits:
        memory: "800Mi"
        cpu: "400m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
