apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpine-pod
  name: alpine-pod
  namespace: ckad-ns2
spec:
  containers:
  - image: alpine
    name: alpine-pod
    command: ['sleep', '600']
    env:
    - name: localport
      valueFrom:
        configMapKeyRef:
          name: ckad-configmap
          key: localport
    - name: external_url
      valueFrom:
        configMapKeyRef:
          name: ckad-configmap
          key: external_url

