apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckad-pvc
  namespace: ckad-ns3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
