apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckad-pv
  labels:
    type: local
  namespace: ckad-ns3
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/antonio/desenvolvimento/cursos/ckad-certification-study/oreilly/certification-study/questions/ckad-pv"
