apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-replica
  name: nginx-replica
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-replica
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 10%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-replica
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
        resources: {}
status: {}
