apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-run
  name: http-run
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-run
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-run
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
