apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-busybox
  name: sidecar-busybox
spec:
  containers:
  - command:
    - echo hello; sleep 3600
    image: busybox
    name: sidecar-busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
