apiVersion: v1
data:
  nginx-custom-config.conf: "server {\n\tlisten\t\t8888;\n\tserver_name\tlocalhost;\n\tlocation
    / {\n\t\troot\t/usr/share/nginx/html;\n\t\tindex\tindex.html index.htm;\n\t}\n}\n\t\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-custom-config
