apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: cm-config
    configMap:
      name: nginx-custom-config
      items:
      - key: nginx-custom-config.conf
        path: default.conf 
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: cm-config
      mountPath: /etc/nginx/conf.d
    env:
      - name: TEST_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sc-config
            key: passphrase
  restartPolicy: Always
